name: user_manager_gk
description: "Ứng dụng quản lý người dùng (CRUD) cho phân hệ Admin – sử dụng Flutter + Firebase."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase core và các dịch vụ
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3

  # Giao diện & icon
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  iconsax: ^0.0.8


  # Ảnh & file picker
  image_picker: ^1.1.2

  # State management
  provider: ^6.1.2

  # Animation & UX
  flutter_animate: ^4.5.0
  lottie: ^3.1.3

  # Tiện ích phụ
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
