// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzCnwBONiwAAdXheZAmlvuYF2JK1rUaxA',
    appId: '1:39244255665:web:43850ab212e0daf0d0ed90',
    messagingSenderId: '39244255665',
    projectId: 'usermanagergk',
    authDomain: 'usermanagergk.firebaseapp.com',
    storageBucket: 'usermanagergk.firebasestorage.app',
    measurementId: 'G-RP6DT408LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU9bIVs-MqDVhsZNlfgt3BPMRYWk5em6w',
    appId: '1:39244255665:android:8f219d8a5a8f5221d0ed90',
    messagingSenderId: '39244255665',
    projectId: 'usermanagergk',
    storageBucket: 'usermanagergk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBliN0PvM-m0dpKW8dhD9Rfpi1GeKic_0',
    appId: '1:39244255665:ios:8f29e04d6be9c64bd0ed90',
    messagingSenderId: '39244255665',
    projectId: 'usermanagergk',
    storageBucket: 'usermanagergk.firebasestorage.app',
    iosBundleId: 'com.example.userManagerGk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBliN0PvM-m0dpKW8dhD9Rfpi1GeKic_0',
    appId: '1:39244255665:ios:8f29e04d6be9c64bd0ed90',
    messagingSenderId: '39244255665',
    projectId: 'usermanagergk',
    storageBucket: 'usermanagergk.firebasestorage.app',
    iosBundleId: 'com.example.userManagerGk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzCnwBONiwAAdXheZAmlvuYF2JK1rUaxA',
    appId: '1:39244255665:web:5bd941d1a0b07c94d0ed90',
    messagingSenderId: '39244255665',
    projectId: 'usermanagergk',
    authDomain: 'usermanagergk.firebaseapp.com',
    storageBucket: 'usermanagergk.firebasestorage.app',
    measurementId: 'G-EQ6FW2L3GQ',
  );
}
